services:
  base:
    image: ${BASE_IMAGE}:fedora${FEDORA_VERSION}
    build:
      context: ./install
      dockerfile: Dockerfile
      args:
        FEDORA_VERSION: ${FEDORA_VERSION}
    volumes:
      # - ../geog_high_res_mandatory:/root/rasp/geog
      - ../geog_low_res_mandatory/WPS_GEOG_LOW_RES:/root/rasp/geog

  run:
    image: ${BASE_IMAGE}:fedora${FEDORA_VERSION}-$REGION
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        FEDORA_VERSION: ${FEDORA_VERSION}
        BASE_IMAGE: ${BASE_IMAGE}
        REGION: ${REGION}
    volumes:
      # - ../geog_high_res_mandatory:/root/rasp/geog
      - ../geog_low_res_mandatory/WPS_GEOG_LOW_RES:/root/rasp/geog
